vich_uploader:
    db_driver: orm

    mappings:
        articles_image:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            namer : Vich\UploaderBundle\Naming\UniqidNamer

            # namer : service qui va nommer chaque image uploadée avec un nom unique
            # upload_destionation : dossier d'upload des images
